HW 10. Hashicorp Vault
otus-kuber-2020-04/ifqthenp_platform pull request #4
Opened 2020-07-12 21:55 UTC by ifqthenp

# Выполнено ДЗ №10

- [x] Основное ДЗ
- [ ] Задание со *

## В процессе сделано:

Сделано всё, кроме последней части (TLS).
Закончу потом, когда будет время (на пенсии скорее всего).

[Подробное описание читайте в README](https://github.com/otus-kuber-2020-04/ifqthenp_platform/blob/kubernetes-vault/kubernetes-vault/README.md)

## Как запустить проект:

- Run Terraform scripts in the `kubernetes-vault/infra` folder to provision GKE cluster
- Run `install.sh` script in the `kubernetes-vault` folder

## Как проверить работоспособность:

- Read the Vault generated output in the console

## PR checklist:

- [x] Выставлен label с номером домашнего задания

2020-07-13 18:15 UTC, Jasstkn requested changes
Добрый день. Вообще включение TLS является обязательным для сдачи домашнего задания, поэтому предлагаю вам не торопиться, а в комфортном темпе все-таки разобраться с этой частью тоже. В лекции вам должны были показывать, как его включать, так что не должно быть большой проблемой. Если все-таки останутся вопросы - пишите :)

2020-07-14 11:16 UTC, ifqthenp commented
> Добрый день. Вообще включение TLS является обязательным для сдачи домашнего задания, поэтому предлагаю вам не торопиться, а в комфортном темпе все-таки разобраться с этой частью тоже. В лекции вам должны были показывать, как его включать, так что не должно быть большой проблемой. Если все-таки останутся вопросы - пишите :)

2020-07-14 11:16 UTC, closed without merging

2020-07-14 11:18 UTC, ifqthenp commented
Ничего страшного, можно не засчитывать ДЗ. Пересматривать лекцию с этим преподавателем выше моих сил.

2020-07-14 11:52 UTC, Jasstkn commented
> Ничего страшного, можно не засчитывать ДЗ. Пересматривать лекцию с этим преподавателем выше моих сил. Разберусь когда будет время.

Если передумаете - пишите :)